export const SET_LOADING = "SET_LOADING";
export const GET_USER = "GET_USER";
export const GET_USER_REQUESTED = "GET_USER_REQUESTED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_REQUESTED = "SET_CURRENT_USER_REQUESTED";
